// actions.js
export const COMMON_FORMS_ACTIONS = {
  SET_STATE_FROM_DATA_LOADING: 'SET_STATE_FROM_DATA_LOADING',
  SET_STATE_FROM_DATA_SUCCESS: 'SET_STATE_FROM_DATA_SUCCESS',
  SET_STATE_FROM_DATA_ERROR: 'SET_STATE_FROM_DATA_ERROR',
  SUBMIT_FORM_LOADING: 'SUBMIT_FORM_LOADING',
  SUBMIT_FORM_SUCCESS: 'SUBMIT_FORM_SUCCESS',
  SUBMIT_FORM_ERROR: 'SUBMIT_FORM_ERROR',
  CHANGE_INPUT: 'CHANGE_INPUT',
}

export const FORM_INVOICE_ACTIONS = {
  ADD_PRODUCT_LINE: 'ADD_PRODUCT_LINE',
  CHANGE_INPUT_PRODUCT: 'CHANGE_INPUT_PRODUCT',
  LOAD_FORM_DATA_LOADING: 'LOAD_FORM_DATA_LOADING',
  LOAD_FORM_DATA_SUCCESS: 'LOAD_FORM_DATA_SUCCESS',
  LOAD_FORM_DATA_ERROR: 'LOAD_FORM_DATA_ERROR',
  SET_DATA_DEEP_CLONE: 'SET_DATA_DEEP_CLONE',
}

export const createAction = (type, payload = {}) => {
  console.log('createAction', type, payload)
  return { type, ...payload }
}
